# Generated by Django 5.2.7 on 2025-10-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_type',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(to='services.servicecategory'),
        ),
    ]
