# Generated by Django 5.2.7 on 2025-10-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='price_per_minute',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
