# Generated by Django 5.2.7 on 2025-10-05 23:21

from django.db import migrations


def create_initial_service_categories(apps, schema_editor):
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    ServiceCategory.objects.bulk_create([
        ServiceCategory(name="Towing", description="Emergency towing services."),
        ServiceCategory(name="Mechanic", description="On-site mechanical repairs."),
        ServiceCategory(name="Vehicle Parts", description="Assistance in finding vehicle parts."),
        ServiceCategory(name="Vulcanizing", description="Tire repair and replacement services."),
        ServiceCategory(name="Washing", description="Vehicle washing and cleaning services."),
    ])

def reverse_initial_service_categories(apps, schema_editor):
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    ServiceCategory.objects.filter(
        name__in=["Towing", "Mechanic", "Vehicle Parts", "Vulcanizing", "Washing"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_pricing_price_per_minute'),
    ]

    operations = [
        migrations.RunPython(create_initial_service_categories, reverse_initial_service_categories),
    ]